# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ugv/UGV_message.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class UGV_message(genpy.Message):
  _md5sum = "541f49227f5e048de585cd06317c60d9"
  _type = "ugv/UGV_message"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 Forward_Right
int32 Reverse_Right
int32 Forward_Left
int32 Reverse_Left

float32 DAC_Right
float32 DAC_Left

int32 Brake_Right
int32 Brake_Left
"""
  __slots__ = ['Forward_Right','Reverse_Right','Forward_Left','Reverse_Left','DAC_Right','DAC_Left','Brake_Right','Brake_Left']
  _slot_types = ['int32','int32','int32','int32','float32','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Forward_Right,Reverse_Right,Forward_Left,Reverse_Left,DAC_Right,DAC_Left,Brake_Right,Brake_Left

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UGV_message, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Forward_Right is None:
        self.Forward_Right = 0
      if self.Reverse_Right is None:
        self.Reverse_Right = 0
      if self.Forward_Left is None:
        self.Forward_Left = 0
      if self.Reverse_Left is None:
        self.Reverse_Left = 0
      if self.DAC_Right is None:
        self.DAC_Right = 0.
      if self.DAC_Left is None:
        self.DAC_Left = 0.
      if self.Brake_Right is None:
        self.Brake_Right = 0
      if self.Brake_Left is None:
        self.Brake_Left = 0
    else:
      self.Forward_Right = 0
      self.Reverse_Right = 0
      self.Forward_Left = 0
      self.Reverse_Left = 0
      self.DAC_Right = 0.
      self.DAC_Left = 0.
      self.Brake_Right = 0
      self.Brake_Left = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i2f2i().pack(_x.Forward_Right, _x.Reverse_Right, _x.Forward_Left, _x.Reverse_Left, _x.DAC_Right, _x.DAC_Left, _x.Brake_Right, _x.Brake_Left))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.Forward_Right, _x.Reverse_Right, _x.Forward_Left, _x.Reverse_Left, _x.DAC_Right, _x.DAC_Left, _x.Brake_Right, _x.Brake_Left,) = _get_struct_4i2f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i2f2i().pack(_x.Forward_Right, _x.Reverse_Right, _x.Forward_Left, _x.Reverse_Left, _x.DAC_Right, _x.DAC_Left, _x.Brake_Right, _x.Brake_Left))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.Forward_Right, _x.Reverse_Right, _x.Forward_Left, _x.Reverse_Left, _x.DAC_Right, _x.DAC_Left, _x.Brake_Right, _x.Brake_Left,) = _get_struct_4i2f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i2f2i = None
def _get_struct_4i2f2i():
    global _struct_4i2f2i
    if _struct_4i2f2i is None:
        _struct_4i2f2i = struct.Struct("<4i2f2i")
    return _struct_4i2f2i
